<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-BillingProcessor.Migration-064d6715-90db-452f-b17c-5caa5e84d1f7</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.6" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BillingProcessor.Repository\BillingProcessor.Repository.csproj" />
    <ProjectReference Include="..\Host.Infrastructure\Host.Infrastructure.csproj" />
    <ProjectReference Include="..\Repository.Infrastructure\Repository.Infrastructure.csproj" />
  </ItemGroup>
</Project>
