// <auto-generated>
//     This code was generated by Refitter.
// </auto-generated>


using Refit;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;

using ConversationAdapter.Contracts.Api;

#nullable enable annotations

namespace ConversationAdapter.Contracts.ApiClient
{
    /// <summary>ConversationAdapter.Host | v1</summary>
    [System.CodeDom.Compiler.GeneratedCode("Refitter", "1.6.1.0")]
    public partial interface IConversationAdapterApiClient
    {
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>OK</description>
        /// </item>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json, application/problem+json", "Content-Type: application/json")]
        [Get("/api/v1/customer-actions/process")]
        Task<IApiResponse<CustomerActionResponse>> ProcessCustomerAction([Body] CustomerActionRequest body, CancellationToken cancellationToken = default);


    }

}