// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PolicyProcessor.Repository;

#nullable disable

namespace PolicyProcessor.Repository.Migrations
{
    [DbContext(typeof(PolicyDbContext))]
    partial class PolicyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PolicyProcessor.Domain.Entities.InsurancePlans.InsurancePlan", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<string>("ChangedOn")
                        .HasMaxLength(48)
                        .HasColumnType("nvarchar(48)");

                    b.Property<string>("CreatedOn")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("nvarchar(48)");

                    b.Property<int>("LifetimeInDays")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PolicyTemplateDocumentId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<decimal>("Price")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<string>("PriceReasoning")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("InsurancePlans", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "01K33RQRZ3MA3CJFR6JMBM8HXF",
                            CreatedOn = "2025-08-21 15:53:44",
                            LifetimeInDays = 7,
                            Name = "Basic Plan",
                            PolicyTemplateDocumentId = "01K33RW7YFCVHMWJM3BT9VSHF8",
                            Price = 25m,
                            PriceReasoning = "This plan provides basic level of protection and services. NOTE: Price is fixed for all clients for this insurance plan."
                        },
                        new
                        {
                            Id = "01K33RT9B4R5H40M0S501EWAYN",
                            CreatedOn = "2025-08-21 15:53:44",
                            LifetimeInDays = 7,
                            Name = "Premium Plan",
                            PolicyTemplateDocumentId = "01K33RWMYKQTSCGBXMWZTQCCKK",
                            Price = 100m,
                            PriceReasoning = "This plan provides premium level of protection and services. NOTE: Price is entity fixed for all clients for this insurance plan."
                        });
                });

            modelBuilder.Entity("PolicyProcessor.Domain.Entities.InsurancePolicies.InsurancePolicy", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<string>("ChangedOn")
                        .HasMaxLength(48)
                        .HasColumnType("nvarchar(48)");

                    b.Property<string>("CreatedOn")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("nvarchar(48)");

                    b.Property<string>("ExpiredAt")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FailureReasoning")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("InsurancePlanId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<string>("IssuedOn")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PolicyDocumentId")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<string>("VehicleId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.HasKey("Id");

                    b.HasIndex("InsurancePlanId");

                    b.HasIndex("UserId", "VehicleId");

                    b.HasIndex("UserId", "VehicleId", "InsurancePlanId");

                    b.ToTable("InsurancePolicies", (string)null);
                });

            modelBuilder.Entity("PolicyProcessor.Domain.Entities.InsurancePolicies.InsurancePolicy", b =>
                {
                    b.HasOne("PolicyProcessor.Domain.Entities.InsurancePlans.InsurancePlan", "InsurancePlan")
                        .WithMany()
                        .HasForeignKey("InsurancePlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InsurancePlan");
                });
#pragma warning restore 612, 618
        }
    }
}
