<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Configurations>Debug;Release;Infra</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UserProcessor.Domain\UserProcessor.Domain.csproj" />
    <ProjectReference Include="..\UserProcessor.Infrastructure\UserProcessor.Infrastructure.csproj" />
  </ItemGroup>

</Project>
