// <auto-generated />
using DocumentProcessor.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DocumentProcessor.Repository.Migrations
{
    [DbContext(typeof(DocumentDbContext))]
    [Migration("20250821155217_AddAuditableFields")]
    partial class AddAuditableFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DocumentProcessor.Domain.Entities.Documents.Document", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<string>("ChangedOn")
                        .HasMaxLength(48)
                        .HasColumnType("nvarchar(48)");

                    b.Property<string>("CreatedOn")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("nvarchar(48)");

                    b.Property<string>("DocumentDownloadUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FileId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.HasKey("Id");

                    b.ToTable("Documents", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "01K33RW7YFCVHMWJM3BT9VSHF8",
                            CreatedOn = "2025-08-21 15:52:16.9885262",
                            DocumentType = "InsurancePolicyTemplate",
                            FileId = "01K33SHJFHVVW9AC1YEC8FJ129"
                        },
                        new
                        {
                            Id = "01K33RWMYKQTSCGBXMWZTQCCKK",
                            CreatedOn = "2025-08-21 15:52:16.9885448",
                            DocumentType = "InsurancePolicyTemplate",
                            FileId = "01K33SKD4PKGDZCG5S73NDD4PP"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
